---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Set up resolv.conf"
  ansible.builtin.template:
    src: "resolv.conf.j2"
    dest: "{{ dns_resolvconf }}"
    owner: 'root'
    group: 'root'
    mode: 'u=rw,go=r'
